### PR TITLE
fix: integrations not loading properly

### LINKED ISSUE #1487: [Bug] Integrations Not Loading Properly for WPUF
**Description:**  While working with various integrations like **Dokan**, **ACF**, **WC Vendors**, and **WCFM**, we've encountered an issue where these integrations are not loading properly in the **WP User Frontend (WPUF)** plugin. These integrations are critical for extending WPUF's capabilities and must work seamlessly for users who rely on them for marketplace and field customization features.

**Affected Integrations:**
- **Dokan**
- **Advanced Custom Fields (ACF)**
- **WC Vendors**
- **WCFM (WooCommerce Frontend Manager)**

**Steps to Reproduce:**
1. Install the WPUF plugin.
2. Ensure the Dokan, ACF, WC Vendors, and WCFM plugins are installed and activated.
3. Attempt to use the form builder or any functionality dependent on these integrations.
4. Observe that the related integrations are not functioning correctly or are not being loaded properly.

**Expected Behavior:**  
- Integrations like Dokan, ACF, WC Vendors, and WCFM should load seamlessly within the WPUF form builder and other relevant functionalities without any issues.
- Users should be able to manage and configure fields or settings specific to these integrations from the WPUF form builder.

**Actual Behavior:**  
- Integrations are not being loaded or managed correctly, resulting in missing features or broken functionalities in the WPUF plugin.

### PR DESCRIPTION
**Pull request by sapayth**
fixes #1487 

`ACF, Dokan, WC Vendors, WCFM` integrations wasn't loading properly with WPUF.

need to test all the integrations. some video references on how the integration works:
[Dokan](https://www.youtube.com/watch?v=6n6CtGjTCF4)
[ACF](https://www.youtube.com/watch?v=AsOkYxRZ6yo&list=PLz-4KMWdVrIzr8BcsPmdVO7tUDNPKfsoc&index=6)
[WC Vendors](https://www.youtube.com/watch?v=gVuB3f8daOw&list=PLz-4KMWdVrIzr8BcsPmdVO7tUDNPKfsoc&index=19)
[WC Marketplace/ WCFM](https://www.youtube.com/watch?v=95OtuSY2JuE&list=PLz-4KMWdVrIzr8BcsPmdVO7tUDNPKfsoc&index=21)

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `Integrations` class to manage various integrations dynamically based on available plugins.
	- Added support for integrations with `Dokan`, `WC Vendors`, `WCMp`, and `ACF`.
	- Improved form submission process with structured validation for form fields.
	- Enhanced form rendering logic with better JavaScript initialization and improved form structure.

- **Improvements**
	- Enhanced the `WP_User_Frontend` class to include an instance of the new `Integrations` class for better integration management.
	- Simplified logic in the `dokan_is_seller_dashboard` method for improved clarity.
	- Minor formatting adjustments in the template files for consistency.

### CODE REVIEW

**Comment by Rat01047** [comment]
`Issue-1:`
From Dokan-Dashboard --> Post Form Submission/creation is not working ---> After Submission the Page just reloads and post is not created

`Additional-info:`
- No Debug log error
- No Console error
- Post not created
- No email log

`Video for reference:`
https://www.awesomescreenshot.com/video/32320868?key=98325190342fb46116fc9ead4d875dbd

**Comment by Rat01047** [comment]
`Issue-2:`
The Post-Form design/style selection is not reflected properly in Dokan-Vendor-Dashboard end ----> I have selected Form-titles to be "Left of Element" i.e. the Titles will be on the left of the Action/Input boxes ----> But here not style is being taken

`Screenshot for reference:`
CleanShot 2024-10-08 at 12  00 55

**Comment by sapayth** [comment]
> `Issue-1:` From Dokan-Dashboard --> Post Form Submission/creation is not working ---> After Submission the Page just reloads and post is not created
> 
> `Additional-info:`
> 
> * No Debug log error
> * No Console error
> * Post not created
> * No email log
> 
> `Video for reference:` https://www.awesomescreenshot.com/video/32320868?key=98325190342fb46116fc9ead4d875dbd

fixed. please have a look now

**Comment by Rat01047** [comment]
`Issue-3:`
In WPUF-Registration form --> WCFM Template is not working even after proper required Plugins are activated

`Screenshot given for reference:`
WCFM-Plugin Active:
CleanShot 2024-10-09 at 2  33 41

WPUF-Registration-WCFM not working:
CleanShot 2024-10-09 at 2  36 50

**Comment by sapayth** [comment]
related [PR](https://github.com/weDevsOfficial/wpuf-pro/pull/641) for WCFM

**Comment by Rat01047** [comment]
@sapayth bhai,
LGTM --> Working as expected 🟢

**Pull request merged**
