### PR TITLE
fix: reset password not working

### PR DESCRIPTION
**Pull request by sapayth**
Using Forgot-password and setting new password is not working ---> The old password is still being used to perform login-action and the new-set password is not working at all

fix [#558](https://github.com/weDevsOfficial/wpuf-pro/issues/558)

### CODE REVIEW

**Comment by Rat01047** [comment]
Issue:
Password reset-email is not showing any content

Scenario:
1. Lost Password -> Enter email to receive Password-reset email
2. Email-sent -> But no content

Screenshots for reference:
[Email-log]
http://tinyurl.com/2cypcp23

http://tinyurl.com/2y99svx2

**Comment by Rat01047** [comment]
Enhancement Request:
Can we add a success message once we click "Get New Password" button

Scenario:
1. Login Page > Click Lost Password
2. Enter Email > Click "Get New Password" button --> Add a success message that Email has been sent to the entered email

Screenshot for reference:
http://tinyurl.com/2468tjlp

**Comment by anik-fahmid** [comment]
@sapayth vai, please add the success messages:

- Scenario 1: Your password has been reset, and the new password has been sent to the email address you provided. 

- Scenario 2: Your password has been successfully reset. You can now log in with your new password.

**Comment by sapayth** [comment]
@anik bhai, we already have translated text for 
Scenario 1: Check your e-mail for the confirmation link.
Scenario 2: Your password has been reset successfully

So continuing with the current messages for now.

**Pull request merged**
