### PR TITLE
Handle custom post statuses in dashboard

### PR DESCRIPTION
**Pull request by jayyx2**

### CODE REVIEW

**Comment by tareq1988** [comment]
Hello @jayyx2, we have filters available on those places. I suggest you use those filters as this is a rare need. I don't think we will merge this for now.

**Comment by jayyx2** [comment]
> Hello @jayyx2, we have filters available on those places. I suggest you use those filters as this is a rare need. I don't think we will merge this for now.

add_filter('wpuf_show_post_status', '<span style="">Declined</span>', 'declined');

Adding this filter doesn't seem to do anything. Am I missing something?

**Comment by jayyx2** [comment]
I can't seem to get this working no matter what I try...

function wpuf_show_post_custom_status($status) {
    if ($status) {
        $title     = $status;
        $fontcolor = '#C00202';
        $show_status = '<span style="color:' . $fontcolor . ';">Undefined'. $title . '</span>';
	return $show_status;}
}

function show_custom_post_status_status_1($status) {
	return $status;
}

function get_all_post_statuses(){
$args = [
    'author'         => get_current_user_id(),
    'post_status'    => ['declined'],
    'post_type'      => $post_type,
    'posts_per_page' => wpuf_get_option( 'per_page', 'wpuf_dashboard', 10 ),
    'paged'          => $pagenum,
];
$dashboard_query2 = new WP_Query($args);
return $dashboard_query2;
}
add_filter('wpuf_dashboard_query', 'get_all_post_statuses');
add_filter('wpuf_show_post_status', 'wpuf_show_post_custom_status', 'show_custom_post_status_status_1');

@tareq1988 please provide some assistance when you have a chance. Thanks so much.

**Comment by jayyx2** [comment]
function wpuf_show_post_custom_status() {
$status = get_post_status($post);
    if ( $status == 'publish' ) {
        $title     = __( 'Live', 'wp-user-frontend' );
        $fontcolor = '#33CC33';
    } elseif ( $status == 'draft' ) {
        $title     = __( 'Offline', 'wp-user-frontend' );
        $fontcolor = '#bbbbbb';
    } elseif ( $status == 'pending' ) {
        $title     = __( 'Awaiting Approval', 'wp-user-frontend' );
        $fontcolor = '#C00202';
    } elseif ( $status == 'future' ) {
        $title     = __( 'Scheduled', 'wp-user-frontend' );
        $fontcolor = '#bbbbbb';
    } elseif ( $status == 'private' ) {
        $title     = __( 'Private', 'wp-user-frontend' );
        $fontcolor = '#bbbbbb';
    } elseif ( $status == 'declined' ) {
        $title     = __( 'Declined', 'wp-user-frontend' );
        $fontcolor = '#C00202';
    } elseif ( $status == 'conditional' ) {
        $title     = __( 'Conditional', 'wp-user-frontend' );
        $fontcolor = '#33CC33';
    } elseif ( $status == 'accepted' ) {
        $title     = __( 'Accepted', 'wp-user-frontend' );
        $fontcolor = '#33CC33';
    } elseif ( $status == 'in-revisions' ) {
        $title     = __( 'In Revisions', 'wp-user-frontend' );
        $fontcolor = '#33CC33';
    } elseif ( $status == 'shortlisted' ) {
        $title     = __( 'Shortlisted', 'wp-user-frontend' );
        $fontcolor = '#33CC33';
    } else {
        $title = $status;
        $fontcolor = '#33CC33';
    }
    $show_status = '<span style="color:' . $fontcolor . ';">' . $title . '</span>';
    return wp_kses_post($show_status);

}
add_filter('wpuf_show_post_status', 'wpuf_show_post_custom_status');

function wpuf_show_post_custom_status_dashboard($dashboard_query) {
$args = array(
    'author'         => get_current_user_id(),
    'post_status'    => ['any'],
    'post_type'      => $post_type
);
return $args;
}
add_filter('wpuf_dashboard_query', 'wpuf_show_post_custom_status_dashboard');


One problem remains: there is no filter for the $show_link in /wp-user-frontend/templates/dashboard/posts.php line 107

                    $show_link        = !in_array( $post->post_status, ['draft', 'future', 'pending'] );

**Pull request closed without merging**
