### PR TITLE
Fix/tax rate not affecting

### PR DESCRIPTION
**Pull request by zamandevs**

### CODE REVIEW

**Comment by tareq1988** [comment]
@zamandevs is the function file has any changes related to this fix? Is it phpcs fixes only?

**Comment by zamandevs** [comment]
@tareq1988 Two commit here. one for fix & another for cs. after i created this PR hasinur bhai informed me he did this before on another PR. phpcs fix need to merge.

**Comment by tareq1988** [comment]
@zamandevs There are misaligned arrays in the functions file because maybe you fixed them with `phpcbf` or `php-cs-fixer`. Those need to be aligned correctly manually.

**Comment by zamandevs** [comment]
@tareq1988 I don't see any alignment issue both on my Phpstorm & also github file editor. i am stuck at this point. besides phpstorm CS is from wordpress. thus i dn't see difference. pls guide me in this regard.

**Pull request merged**
